{
  "Message": "HandlingInstanceID: 4e09df04-0b80-4373-b750-e41079a43c51\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:30:07\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfExceptionHandlingDemo.ViewModels.MainViewModel.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\ViewModels\\MainViewModel.cs:line 54\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:30:07 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.vshost.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:30:07.5507266Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.vshost.exe",
  "ProcessId": "7848",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.vshost.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "2412",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:30:07 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: b27af0fd-19b0-49b7-adbf-6b786c507d61\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:32:04\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfExceptionHandlingDemo.ViewModels.MainViewModel.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\ViewModels\\MainViewModel.cs:line 54\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:32:04 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.vshost.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:32:04.3492036Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.vshost.exe",
  "ProcessId": "7344",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.vshost.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "9256",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:32:04 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: cab1a2e8-bd8a-4654-8605-ef26bc8069d0\r\nAn exception of type 'System.ApplicationException' occurred and was caught.\r\n---------------------------------------------------------------------------\r\n03/15/2015 15:33:23\r\nType : System.ApplicationException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Original exception wrapped. Check inner exception.\r\nSource : \r\nHelp link : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : \r\nHResult : -2146232832\r\nStack Trace : The stack trace is unavailable.\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:33:23 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.vshost.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n\tInner Exception\r\n\t---------------\r\n\tType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\n\tMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\n\tSource : mscorlib\r\n\tHelp link : \r\n\tFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\n\tFusionLog : \r\n\tData : System.Collections.ListDictionaryInternal\r\n\tTargetSite : Void WinIOError(Int32, System.String)\r\n\tHResult : -2147024894\r\n\tStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n\t   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n\t   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n\t   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n\t   at WpfExceptionHandlingDemo.ViewModels.MainViewModel.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\ViewModels\\MainViewModel.cs:line 54\r\n\t   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:33:24.1928192Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.vshost.exe",
  "ProcessId": "8132",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.vshost.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "9460",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:33:24 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: 897932dc-b914-438e-9bad-6eafd965954e\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:35:30\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfExceptionHandlingDemo.ViewModels.MainViewModel.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\ViewModels\\MainViewModel.cs:line 54\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:35:31 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.vshost.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:35:31.1859718Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.vshost.exe",
  "ProcessId": "9604",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.vshost.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "3544",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:35:31 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: 6fac1c84-70ae-45bd-b5e5-3bc30cfa0031\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:37:11\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfExceptionHandlingDemo.ViewModels.MainViewModel.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\ViewModels\\MainViewModel.cs:line 54\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:37:11 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.vshost.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:37:11.6363574Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.vshost.exe",
  "ProcessId": "8508",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.vshost.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "7624",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:37:11 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: 61e2078e-2a8e-4a6a-a787-08146b6cc820\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:37:41\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfExceptionHandlingDemo.ViewModels.MainViewModel.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\ViewModels\\MainViewModel.cs:line 54\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:37:41 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.vshost.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:37:42.1840284Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.vshost.exe",
  "ProcessId": "5508",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.vshost.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "6528",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:37:42 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: c56825e2-adfa-4ea6-bdd9-53a7369099f7\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:38:12\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfExceptionHandlingDemo.ViewModels.MainViewModel.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\ViewModels\\MainViewModel.cs:line 54\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:38:12 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.vshost.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:38:12.6090778Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.vshost.exe",
  "ProcessId": "5508",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.vshost.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "6528",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:38:12 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: 982fab3f-b1ec-417b-9574-e3f351c8030b\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:38:26\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfExceptionHandlingDemo.ViewModels.MainViewModel.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\ViewModels\\MainViewModel.cs:line 54\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:38:26 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.vshost.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:38:26.5452737Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.vshost.exe",
  "ProcessId": "3528",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.vshost.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "9488",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:38:26 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: e41ca669-b9a9-4df3-aa0a-45ea8e904aa0\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:50:39\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 60\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:50:39 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.vshost.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:50:39.7832887Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.vshost.exe",
  "ProcessId": "11164",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.vshost.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "8620",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:50:39 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: c87822c2-e5ab-4cad-80ad-bf6b3949cbda\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:51:50\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 60\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:51:50 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.vshost.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:51:50.7322575Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.vshost.exe",
  "ProcessId": "10708",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.vshost.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "2944",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:51:50 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: c66367cb-14b9-4ee5-b3c5-bbbe1bc4695c\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:52:02\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 60\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:52:02 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.vshost.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:52:02.7256541Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.vshost.exe",
  "ProcessId": "10708",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.vshost.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "2944",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:52:02 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: 34f643cf-d213-4532-b7ed-0f08d9a2156f\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:52:10\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 60\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:52:10 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.vshost.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:52:10.5800395Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.vshost.exe",
  "ProcessId": "10708",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.vshost.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "2944",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:52:10 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: b72eff04-2dd1-4ca0-b470-a4c1e89d4cdf\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:52:22\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 60\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:52:22 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.vshost.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:52:22.6505258Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.vshost.exe",
  "ProcessId": "10708",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.vshost.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "2944",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:52:22 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: a8165420-94ad-4e0e-8ab4-b0d9f7b512b0\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:52:45\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 60\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:52:45 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.vshost.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:52:45.5891554Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.vshost.exe",
  "ProcessId": "10708",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.vshost.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "2944",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:52:45 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: ad8a1e3d-d127-499a-9468-5377a4736433\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:54:55\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 61\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:54:55 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.vshost.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:54:55.893097Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.vshost.exe",
  "ProcessId": "9000",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.vshost.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "8064",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:54:55 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: 2203b0ee-9cb1-4681-acae-ba1c0f46a258\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:54:59\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 61\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:54:59 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.vshost.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:54:59.1908741Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.vshost.exe",
  "ProcessId": "9000",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.vshost.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "8064",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:54:59 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: c3126c11-3975-4581-91fc-4c89329e9622\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:58:23\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 59\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:58:23 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.vshost.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:58:23.320224Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.vshost.exe",
  "ProcessId": "2532",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.vshost.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "7948",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:58:23 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: b3bccd46-e0ce-4120-9469-1013a5640357\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:58:29\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 59\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:58:29 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.vshost.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:58:29.0478217Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.vshost.exe",
  "ProcessId": "2532",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.vshost.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "7948",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:58:29 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: 2b3593b4-3b5a-4d76-ac8e-a2877d0a653e\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:58:41\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 59\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:58:41 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.vshost.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:58:41.4973602Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.vshost.exe",
  "ProcessId": "2532",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.vshost.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "7948",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:58:41 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: 568c6170-935c-47b6-abea-605cfcf9d51d\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:58:52\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 59\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:58:52 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.vshost.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:58:52.164979Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.vshost.exe",
  "ProcessId": "2532",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.vshost.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "7948",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:58:52 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: 9f6ddae7-5d31-4119-b4b5-68b844aea841\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:59:29\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 60\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:59:29 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.vshost.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:59:29.3915927Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.vshost.exe",
  "ProcessId": "7032",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.vshost.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "3220",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:59:29 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: 563e59fd-6acd-4b75-bcc4-426301c0c85a\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:59:50\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 60\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:59:50 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:59:50.9411871Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.exe",
  "ProcessId": "10292",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "4292",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:59:50 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: 504ba83b-b1fb-435a-9f2c-72155d20644b\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:59:51\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 60\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:59:51 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:59:51.3477541Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.exe",
  "ProcessId": "10292",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "4292",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:59:51 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: 68cbd3aa-4542-4a00-b08b-725c23e0a998\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:59:52\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 60\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:59:52 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:59:52.0206813Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.exe",
  "ProcessId": "10292",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "4292",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:59:52 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: fd3a2710-f1a7-4353-b654-9659445938fc\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:59:52\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 60\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:59:52 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:59:52.4806192Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.exe",
  "ProcessId": "10292",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "4292",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:59:52 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: a7904aca-aa2a-469c-a584-304c3ee95968\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:59:53\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 60\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:59:53 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:59:53.0200067Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.exe",
  "ProcessId": "10292",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "4292",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:59:53 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: a558a874-e78b-459b-a953-182c09cec70b\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:59:53\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 60\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:59:53 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:59:53.2439715Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.exe",
  "ProcessId": "10292",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "4292",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:59:53 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: b2574eea-fc07-41be-a4a8-cec01d708daa\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 15:59:53\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 60\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 7:59:53 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T19:59:53.4303636Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.exe",
  "ProcessId": "10292",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "4292",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 7:59:53 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: 34e98794-eb8f-45fe-857a-257d0a13d1e1\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 16:01:41\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 59\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 8:01:41 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.vshost.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T20:01:42.0397397Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.vshost.exe",
  "ProcessId": "8348",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.vshost.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "9032",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 8:01:42 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: 0e4707ba-11e0-4e92-b912-6858dceab97f\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 16:03:58\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 59\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 8:03:58 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T20:03:58.7694685Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.exe",
  "ProcessId": "11104",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "10296",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 8:03:58 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
{
  "Message": "HandlingInstanceID: 7f3022f5-3349-42d6-8012-d287707a67ce\r\nAn exception of type 'System.IO.FileNotFoundException' occurred and was caught.\r\n-------------------------------------------------------------------------------\r\n03/15/2015 16:03:59\r\nType : System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage : Could not find file '\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt'.\r\nSource : mscorlib\r\nHelp link : \r\nFileName : \\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\myfakefile.txt\r\nFusionLog : \r\nData : System.Collections.ListDictionaryInternal\r\nTargetSite : Void WinIOError(Int32, System.String)\r\nHResult : -2147024894\r\nStack Trace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.Open(String path, FileMode mode, FileAccess access)\r\n   at WpfLoggingDemo.MainWindow.<>c__DisplayClass1.<OpenFile>b__0() in \\\\psf\\home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\MainWindow.xaml.cs:line 59\r\n   at Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ExceptionManager.Process[TResult](Func`1 action, TResult defaultResult, String policyName)\r\n\r\nAdditional Info:\r\n\r\nMachineName : LORILALONDE1F65\nTimeStamp : 3/15/2015 8:03:59 PM\nFullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nAppDomainName : WpfExceptionHandlingDemo.exe\nThreadIdentity : \nWindowsIdentity : LORILALONDE1F65\\lorilalonde\n",
  "Categories": [
    "General"
  ],
  "Priority": 0,
  "EventId": 100,
  "Severity": 2,
  "LoggedSeverity": "Error",
  "Title": "Enterprise Library Exception Handling",
  "TimeStamp": "2015-03-15T20:04:00.0002642Z",
  "MachineName": "LORILALONDE1F65",
  "AppDomainName": "WpfExceptionHandlingDemo.exe",
  "ProcessId": "11104",
  "ProcessName": "\\\\psf\\Home\\Documents\\Apress\\ProXaml\\Source Code\\CH07\\WpfExceptionHandlingDemo\\WpfExceptionHandlingDemo\\bin\\Debug\\WpfExceptionHandlingDemo.exe",
  "ManagedThreadName": null,
  "Win32ThreadId": "10296",
  "ExtendedProperties": {},
  "TimeStampString": "3/15/2015 8:04:00 PM",
  "ActivityId": "00000000-0000-0000-0000-000000000000",
  "RelatedActivityId": null,
  "ErrorMessages": null,
  "ActivityIdString": "00000000-0000-0000-0000-000000000000",
  "CategoriesStrings": [
    "General"
  ]
}
